apiVersion: v1
kind: Service
metadata:
  labels:
    run: todo-app
  name: todo-service
  namespace: default
spec:
  ports:
  - nodePort: 32166
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    run: todo-app
  sessionAffinity: None
  type: LoadBalancer
